
version: 2

models:

  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: random_for_practice
    description: "this is to practice"
    columns:
      - name: id
        tests:
          - unique
          - not_null
    
  - name: transformation_practice
    description: "this is for transformation practice"
    columns:
      - name: new_id
        tests:
          - unique
          - not_null

  - name: increamental_practice
  - name: random_date
  - name: snowflake_customers_purchases

sources:
  - name: sample
    database: snowflake_sample_data  # Tell dbt to look for the source in the "raw" database
    schema: tpch_sf1
    tables:
      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
      - name: orders
  # - name: sample2
  #   database: snowflake_sample_data
  #   schema: tpch_sf001
  #   tables:
  #     - name: customer