name: Auto create PR  
on:
    push:
        branches:    
            - dev
 
jobs:
    createPullRequest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Raise PR
              uses: peter-evans/create-pull-request@v3
              with:
                branch: "dev"
                base: main
                title: "demo for auto pr"
                reviewers: yashagrawal3107

      
